version: '3'
services:
  ars-tts:
    container_name: ars-tts
    image: eclipse-temurin:8u382-b05-jdk-jammy
    volumes:
      - ./app:/opt/app
      - ./logs:/spring-log
    environment:
      - PROFILES_ACTIVE=prod
      - LOGGER_LEVEL=info
      - SERVER_PORT=8080
    entrypoint: ["java", "-jar", "/opt/app/ars-tts-1.0.0.jar"]
    restart: always
    network_mode: "host"
    privileged: true